#!/usr/bin/env bash
# Rejects links to private coding sessions in commit messages.
#
# Usage:
#   scripts/check-private-links.sh [commit-range]
#
# The range defaults to origin/main..HEAD, so running it with no arguments
# before opening a pull request checks exactly the commits you are proposing.
# CI passes the pull request's base..head range.
set -euo pipefail

range="${1:-origin/main..HEAD}"

# Session links are generated by tooling, so match the URL, the commit trailer,
# and the bare session identifier. Extend this list if other hosts appear.
pattern='claude\.ai/[A-Za-z0-9_./-]*session|[Cc]laude-[Ss]ession:|session_[A-Za-z0-9]{16,}'

if ! git rev-parse --quiet --verify "${range%%..*}^{commit}" >/dev/null 2>&1; then
  echo "check-private-links: cannot resolve range '$range'" >&2
  exit 2
fi

status=0
while IFS= read -r sha; do
  [ -n "$sha" ] || continue
  message="$(git log -1 --format=%B "$sha")"
  if printf '%s\n' "$message" | grep -Eq "$pattern"; then
    printf 'Private session link in commit %s (%s):\n' \
      "$sha" "$(git log -1 --format=%s "$sha")"
    printf '%s\n' "$message" | grep -nE "$pattern" | sed 's/^/  /'
    status=1
  fi
done < <(git rev-list "$range")

if [ "$status" -ne 0 ]; then
  cat >&2 <<'EOF'

Commit messages must not link to private coding sessions (CONTRIBUTING.md).
Reword the offending messages before pushing:
  git commit --amend          # most recent commit
  git rebase -i <base-commit> # older commits, choose "reword"
EOF
fi

exit "$status"
